#!/bin/sh
#PBS -S /bin/sh
#PBS -P ds12
#PBS -q normal
#PBS -l walltime=10:00:00,mem=9GB,ncpus=10
#PBS -m abe
#PBS -N Himawari
#PBS -o Himawari.out
#PBS -e Himawari.err
#PBS -l storage=gdata/rv74

echo ""
echo "start job script"
module load python3/3.10.0
module load netcdf/4.6.3
module load openmpi/4.1.1


export PYTHONPATH=$PYTHONPATH:/home/660/sw8035/.local/lib/python3.10/site-packages

cd /scratch/ds12/sw8035

mpirun -np 10 python3 Extract_Himawari.py
