#!/bin/sh
#PBS -S /bin/sh
#PBS -P ds12
#PBS -q normal
#PBS -l walltime=1:00:00,mem=30GB,ncpus=10
#PBS -m abe
#PBS -N BARRA1
#PBS -o BARRA1.out
#PBS -e BARRA1.err
#PBS -l storage=gdata/ob53

echo ""
echo "start job script"
module purge
module load python3/3.10.0
module load openmpi/4.1.1
#module load netcdf/4.6.3

export PYTHONPATH=$PYTHONPATH:/home/660/sw8035/.local/lib/python3.10/site-packages

cd /scratch/ds12/sw8035

mpirun -np 10 python3 Extract_BARRA_C2.py
